Harmonic thermodynamics finished
crystal-code-tools/crystal_functions pull request #28
Opened 2022-07-05 09:14 UTC by Spica-Vir

@bcamino 
Waiting for the discussion with Nic this Wed. I'll inform you ASAP

2022-07-05 09:16 UTC, bcamino commented
Hi @Spica-Vir, thank you very much for this. I will start commenting and wait for your message to let me know you are ready to merge.

Cheers,

Bruno

2022-07-12 07:20 UTC, bcamino commented
@Spica-Vir, Sorry for the delay, I am going to have a look at this asap.

2022-07-12 09:17 UTC, bcamino requested changes
Hi @Spica-Vir , thank you very much for this. I left some comments in the code, please feel free to comment on them too. Cheers, Bruno

2022-07-12 09:17 UTC, bcamino commented on crystal_functions/file_readwrite.py
> +                        np.matrix(self.atom_positions)[:,:dimensionality], lattice[:dimensionality,:dimensionality])
great for the dimensions of the array, but please rever np.matrix to np.array

2022-07-12 09:17 UTC, bcamino commented on crystal_functions/file_readwrite.py
> +    By Spica. Vir., ICL. Jun. 01, 2022.
Please remove names from the code. There is no need for this since GitHub tracks contributions line by line

2022-07-12 09:17 UTC, bcamino commented on crystal_functions/file_readwrite.py
> +    """
Add a check that the output file is a freq calculation. Maybe have that as an attribute in the read_cry_output function like: self.is_freq = True if some freq specific keyword is in the output.

2022-07-12 09:17 UTC, bcamino commented on crystal_functions/thermodynamics.py
> +By Spica. Vir., ICL.
remove

2022-07-12 09:17 UTC, bcamino commented on crystal_functions/thermodynamics.py
> +Last Update: Jul. 04, 2022
this is done by git and github already

2022-07-12 09:17 UTC, bcamino commented on tutorial/thermodynamics/Harmonic_Approx.ipynb
> +{
This is great. Would you mind also adding an example/thermodynamics.ipynb file where you just show the functioning of the functions? Basically this tutorial minus the text.

2022-07-12 17:54 UTC, Spica-Vir commented on crystal_functions/file_readwrite.py
> +
Please ignore these blank lines - I accidentally launched auto PEP8 and modified the spaces and blank lines to meet the PEP8 standard. That doesn't interfere the functionalities.

2022-07-12 19:35 UTC, Spica-Vir reviewed
@bcamino Hi Bruno, modifications are made according to your suggestions. To summarize, a check_freq_file() method is added; option 'errors=ignore' is added to skip the non-utf-8 encoded character when using 'def2-mSVP' basis set. An example is also uploaded. Please note that I haven't finished the quasi-harmonic part, so the example will be updated later.

2022-07-19 08:43 UTC, merged